# Directories to lint
included:
  - BaseApp
  - UnitTests

# Directories to not lint
excluded:
  - Pods
  - fastlane
  - BaseAppV2IntegrationTests
  - BaseAppV2UITests

# Rules to enabled that aren't by default
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - sorted_imports
  - trailing_closure
  - vertical_parameter_alignment_on_call

# Disable default rules
disabled_rules:
  - cyclomatic_complexity
  - empty_enum_arguments
  - file_length
  - function_body_length
  - multiple_closures_with_trailing_closure
  - private_over_fileprivate
  - todo
  - trailing_whitespace
  - valid_ibinspectable
  - vertical_whitespace

# Where to report warnings and errors
reporter: "xcode"

# Customize default rules
function_parameter_count: 6
large_tuple: 4
line_length: 110
type_body_length: 100
warning_threshold: 1